### ISSUE TITLE
The documentation is really very bad...

### ISSUE THREAD

**Issue by husnusdigitalrealty** [milestonetg/transient-fault-handling#2]
Hi, 
I tried to use this library to handle transient errors but the documentation is really very bad and not explicit.  how can I test the handled exception and log it before it tries to retry(an example of polly is shown below)?

`Policy.Handle<SqlException>(exception=>TransientErrorDetection.IsTransient(exception)).
                    WaitAndRetryAsync(RetryPolicyProperties.NumberOfRetries,
                    retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
                    (exception, timeSpan, retryCount, context) =>
                    {
                        LogDetails(exception, timeSpan, retryCount);
                    });` 

Any help will be very appreciated..
Thanks in advance

**Comment by jpenniman** [comment]
You can implement the [`RetryPolicy.Retrying`](https://milestonetg.github.io/transient-fault-handling/api/MilestoneTG.TransientFaultHandling.RetryPolicy.html#events) event.  The [`RetryingEventArgs`](https://milestonetg.github.io/transient-fault-handling/api/MilestoneTG.TransientFaultHandling.RetryingEventArgs.html) contains the retry count and the original exception that caused the retry.

``` cs
retryPolicy.Retrying += (sender, args) =>
{
    logger.Warning("Retry attempt {retry}. Next rety in {delay} Original exception {exception}", args.CurrentRetryCount, args.Delay, args.LastException 
};
```

For databases, any of the DbCommand.ExecuteXxxxxxWithRetry() methods have an overload that takes a custom RetryPolicy, so a complete example would be something like:

```cs
RetryPolicy retryPolicy = new RetryPolicy<SqlDatabaseTransientErrorDetectionStrategy>(3);
retryPolicy.Retrying += (sender, args) =>
{
    logger.Warning("Retry attempt {retry}. Next rety in {delay} Original exception {exception}", args.CurrentRetryCount, args.Delay, args.LastException 
};            

using (DataReader reader = command.ExecuteReaderWithRetry(retryPolicy)) {
...
}
```

**Comment by husnusdigitalrealty** [comment]
Many thanks @jpenniman
